### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by robbeblock** [RedTurtle/eve-sqlalchemy#79] opened 2015-10-20 13:32 UTC
Both the examples in the example dir are not working, in particular when running trivial.py and surfing to http://127.0.0.1:5000/people, I get the following error:

> # sqlalchemy.exc.OperationalError
> 
> OperationalError: (sqlite3.OperationalError) no such column: People [SQL: u'SELECT count(*) AS count_1 \nFROM (SELECT People) AS anon_1']

Am I missing something?

**Comment by botzill** [comment] 2015-10-26 10:35
I also encounter this issue. Plus, when I try to run `sqla_example.py` I get:

<code>
Traceback (most recent call last):
  File "sqla_example.py", line 6, in <module>
    app = Eve(validator=ValidatorSQL, data=SQL)
  File "/Users/chirgeo/.virtualenvs/tests/lib/python2.7/site-packages/eve/flaskapp.py", line 172, in __init__
    self.register_resource(resource, settings)
  File "/Users/chirgeo/.virtualenvs/tests/lib/python2.7/site-packages/eve/flaskapp.py", line 801, in register_resource
    self._validate_resource_settings(resource, settings)
  File "/Users/chirgeo/.virtualenvs/tests/lib/python2.7/site-packages/eve/flaskapp.py", line 322, in _validate_resource_settings
    self.validate_schema(resource, settings['schema'])
  File "/Users/chirgeo/.virtualenvs/tests/lib/python2.7/site-packages/eve/flaskapp.py", line 394, in validate_schema
    "'%s'" % id_field)
eve.exceptions.SchemaException: 'unique' key is mandatory for id field '_id'
</code>

**Comment by botzill** [comment] 2015-10-26 12:54
OK, seems that we get this issue when testing with eve==0.6. I just tested it with 0.5.3 and it works OK.

**Comment by waynew** [comment] 2015-11-05 15:36
I can also confirm this - both the error and that rolling back to eve 0.5.3 is a workaround.

The problem has something to do with the way that eve is building up the query, I expect, because it's using the class name (`People`) rather than the column. It most definitely shouldn't be `(SELECT People)` in there, it should probably just be `SELECT count(*) AS count_1 FROM people AS anon_1`, so something is barfing on that table substitution.

**Comment by Hedde** [comment] 2015-11-11 13:43
confirmed

**Comment by jeroenes** [comment] 2015-11-12 08:16
I got my pre-0.6 code running under eve 0.61 by removing all references to _id and setting the identifier to id throughout,  using the new identifier information. Hope this works  here as well.

And I can confirm the issue with the OperationalError BTW ;-)  Started to notice it with my own code, see https://groups.google.com/forum/m/#!topic/python-eve/zy9x2CTubek .

Would greatly appreciate a resolve or work around. Would also be willing to look at it myself, but I would need some pointer about where to start, this is my first project in python (switching from almost two decades in perl ...)

Best regards, 
Jeroen

**Comment by bthorben** [comment] 2015-11-21 14:00
I have exactly the same problem. And downgrading to eve 0.5.3 also solves the problem.

**Comment by m3talstorm** [comment] 2015-11-29 19:45
Ditto.

pip install eve==0.5.3

does the trick :)

**Comment by ralphsmith80** [comment] 2015-12-24 00:42
Confirmed

eve 0.5.3 works.

The issue is with [Eve](https://github.com/nicolaiarocci/eve/blob/6d22d365915f503ad99680d5bd8c7aea84504345/eve/flaskapp.py#L395).  I'll be testing this shortly but the [docs](http://python-eve.org/validation.html#schema-validation) provide a way to override the default schema validation.

**Comment by ralphsmith80** [comment] 2015-12-24 01:15
I opened an issue in [Eve](https://github.com/nicolaiarocci/eve) the override in the docs isn't working.

**Comment by ralphsmith80** [comment] 2016-02-29 18:08
@nicolaiarocci resolved the issue on the Eve end. I've tested this with Eve `0.6.2.dev0` without issue. Others should check but this could probably be closed now.

**Comment by dkellner** [comment] 2017-02-27 12:06
At the moment running `sqla_example.py` doesn't work because of another issue related to relative imports. I will close this as the issues here have been fixed and will open a new one.

**Closed by dkellner** 2017-02-27 12:06 UTC
