### ISSUE TITLE
Unable to insert JSON data into database

### ISSUE THREAD

**Issue by bomb-on** [RedTurtle/eve-sqlalchemy#124] opened 2017-01-09 16:07 UTC
I have created very simple [EVE testing project](https://github.com/bomb-on/evetest) with [very simple testing table](https://github.com/bomb-on/evetest/blob/master/evetest/models/models.py), obviously just for testing purposes :)

I am trying to insert JSON payload in [`user_data` column](https://github.com/bomb-on/evetest/blob/master/evetest/models/models.py#L15).

I created a simple client which is using [`Requests` library](http://docs.python-requests.org/en/master/) and it looks like this:

```
import requests

payload = {
        'user_id': '1',
        'user_data': {
            'data_type': 'json',
            'data': [
                {'some': 'data', 'which': 'is', 'json': 'formatted'}
            ]
        },
    }
resp = requests.post(url, json=payload)
print(resp.status_code)
```

The error I am getting for this request is `422`:

```
{
    "_error": {
        "code": 422,
        "message": "Insertion failure: 1 document(s) contain(s) error(s)"
    },
    "_issues": {
        "user_data": "must be of string type"
    },
    "_status": "ERR"
}
```

I tried to change `user_data` column type to `sqlalchemy.JSON` along with altering the table in the database itself, but I keep getting the same error.

What I would like to do here is to insert `user_data` object from the request as a string in the table, so I wonder if this is possible somehow "out-of-the-box" (e.g. extending `DOMAIN` definitions with some extra stuff) or should I handle this by myself in some hooks or whatever else?

Thanks a bunch for any help! ;)

**Comment by wjdecorte** [comment] 2017-01-09 23:21
I created a fix for this, but haven't done a pull request for merging it.  I'm still learning the process.  

The problem is that it currently adds postgresql.JSON to the sqla_type_mapping, but ignores the generic SQLA JSON type.  The code snippet below is the fix I used:
```python
def get_sqla_type_mapping():
    try:
        sqla_type_mapping[postgresql.JSON] = 'json'
    except AttributeError:
        # NOTE(Gonéri): JSON has been introduced in SQLAlchemy 0.9.0.
        pass
    try:
        sqla_type_mapping[types.JSON] = 'json'
    except AttributeError:
        # NOTE: Added generic JSON type
        pass
    # TODO: Add the remaining sensible SQL types
    return sqla_type_mapping
```

In your model be sure to define the column with the type JSON imported from sqlalchemy

Hope this helps!

**Comment by dkellner** [comment] 2017-01-15 10:39
@wjdecorte Are you still working on a PR for this? I'd like to include this in the upcoming 0.5 release. If you're not working on this anymore, please let us know so someone else can take over. Thank you!

**Comment by bomb-on** [comment] 2017-01-15 10:43
@dkellner I was thinking to create PR for this, but I just wanted to finish up with another PR regarding Eve itself and then to take a good look at what's going on with this JSON thingie :) Of course, if @wjdecorte would like to submit PR I'm pretty fine with it also :)

**Comment by wjdecorte** [comment] 2017-01-16 02:56
@bomb-on go ahead and submit a PR.  I'm new to this and unfamiliar with the process.  I don't want to hold up changes because my lack of knowledge.

**Comment by dkellner** [comment] 2017-01-16 03:11
@wjdecorte If you like to do this and learn, go ahead! We will be happy to answer questions and provide guidance. Don't worry about deadlines, we're all doing this voluntarily and are happy about new people to support.

So a short summary of how I would tackle this would be:
1. Fork the repo (if you haven't done already).
2. Create a new branch, maybe just `json`, or `fix-124`.
3. Get familiar with running the tests using `tox`. They should all pass as you branched from `master`.
4. Add a new (failing) test for the described issue/bug.
5. Apply your fix and hope all tests will pass :).
6. Push your changes to your Fork/branch and create a PR using the web interface.

**Comment by joystein** [comment] 2017-01-16 10:15
@dkellner what about adding those instructions to a "how to contribute" section in the docs?

**Comment by bomb-on** [comment] 2017-01-16 10:17
@wjdecorte 
What @dkellner said :) I believe there is no extreme rush :) Eve documentation has a pretty nice article about [contributing](http://python-eve.org/contributing.html), I would suggest you to read it, it might clarify lots of things in the process, definitely did for me. Don't be afraid to click on few interesting links in that document, like ["Fork a repo"](https://help.github.com/articles/fork-a-repo/), ["Syncing a fork"](https://help.github.com/articles/syncing-a-fork/) and ["About pull requests"](https://help.github.com/articles/about-pull-requests/), all of them should be extremely helpful! Also, feel free to ask anyone around here or even join the `python-eve` channel on IRC (@dkellner you too ;)), I usually hang around in there most of the day :)
I will continue working on this issue today, just because I need it for my project. I have in plan to take a good look at `get_sqla_type_mapping()` function and "improve", "optimise", "fix" it, or whichever term is applicable here, and try to write some tests for it. However, @wjdecorte, I would give you opportunity to contribute and learn the process if you'd like to ;)

**Comment by bomb-on** [comment] 2017-01-16 10:23
@joystein This is exactly what I wanted to suggest :) I believe we can re-use lots of instructions from [mentioned article](http://python-eve.org/contributing.html). I might even do it myself sometimes today...
What do you think about it @dkellner?

**Comment by joystein** [comment] 2017-01-16 10:32
@bomb-on just having a link to the content you mention would be useful as a starting point.

**Comment by dkellner** [comment] 2017-01-16 16:40
I agree with @joystein, I think linking Eve's documentation should suffice and we don't need to duplicate information. If there's anything missing it's probably useful for Eve as well. However, we should be precise about possible differences between Eve und Eve-SQLAlchemy, if any. But I don't think we will encounter any for the "How to Contribute" page.

**Comment by dkellner** [comment] 2017-01-17 03:27
@bomb-on Well, you're right. I just saw the links to GitHub docs and other generic resources in the beginning. So let's do our own "How to contribute" page to have a consistent version and not confusing newcomers. But we should state that problems/features that are not datalayer-specific should be tackled in Eve directly. And include a comment that it is based on Eve's content. I will create an own issue for this, at is is quite off-topic here :).

**Closed** 2017-02-03 09:59 UTC

**Comment by wjdecorte** [comment] 2017-02-25 21:00
@bomb-on @dkellner 
Thank you for taking care of the issue and adding it the release.  I'm sorry for not getting back to you.  I appreciate the chance to learn the process, but unfortunately work was quite busy the past month and I'm just now able to breath again.  I'll review the information provided above to perhaps help with an issue in the future.  It's impressive to see so much activity and work being completed on this project.
