### ISSUE TITLE
SQLAlchemy JSON support is missing

### ISSUE THREAD

**Issue by wjdecorte** [RedTurtle/eve-sqlalchemy#122] opened 2016-11-16 02:08 UTC
Support for postgresql.JSON was added in 0.3.2, but that does not work with sqlalchemy.JSON.  The type is defined as string in the schema for a column that is type sqlalchemy.JSON.  I think an update to decorators.py in the function get_sqla_type_mapping will be a quick fix.  By adding sqlalchemy.JSON to the dictionary of types should resolve the incompatibility issue.  Currently columns of type sqlalchemy.JSON are set to "string".  This causes an error during the POST when the data is JSON and not string.

**Comment by dkellner** [comment] 2017-01-15 10:41
Closing as duplicate of #124.

**Closed by dkellner** 2017-01-15 10:41 UTC
